name: Deploy to Railway

on:
  push:
    paths:
      - 'path/to/your/microservice/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test phase
        run: echo "Running tests..." # Aquí más adelante se puede usar `./mvnw test` o `./gradlew test`

      - name: Build JAR
        run: ./mvnw clean package -DskipTests # O `./gradlew build -x test`

      - name: Deploy to Railway
        run: |
          curl -Ls https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
          railway login --apiToken ${{ secrets.RAILWAY_API_TOKEN }}
          railway up --service 9e1064b8-6c15-4b28-9b33-9634f935cae1
