name: Deploy Frontend to Railway

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "$RAILWAY_TOKEN" | railway login --ci

      - name: Run tests (placeholder)
        run: echo "Running frontend tests..."

      - name: Build and deploy to Railway
        run: railway up --service bb66ca62-8f35-4881-9fff-2b4fa157b4f5
