name: Deploy Users Service to Railway

on:
  push:
    paths:
      - 'users/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "$RAILWAY_TOKEN" | railway login --ci

      - name: Running tests
        run: echo "Running tests (placeholder)..."

      - name: Build and deploy to Railway
        run: railway up --service 8ed81602-e673-464d-b495-1830b068e034
